### ISSUE TITLE
Resync after adding repos

### ISSUE THREAD

**Issue by NathanHazout** [atlassian/github-for-jira#1025]
Let's say I chose to sync only selected repositories (as opposed to "All repositories").  
When I add new repos to the watch list from the GitHub side of things, when will JIRA pick it up?
Do I have to manually trigger a "Restart backfill" for it to detect the new repo?

**Comment by mboudreau** [comment]
Sadly, yes.  There's no way around this as of this moment because this is a limitation of Github itself.  We only get access and webhooks from those repositories that has been selected.  

However, we are looking to add a feature that will 'backfill' the new repository added to the selected list when an event happens.  We've started added the foundations to make this a possibility and hoping to add this in in the coming weeks/months.

Cheers.

**Comment by NathanHazout** [comment]
Thanks, to clarify, if I don't click on backfill, will NEW events still reach JIRA?  
Or do I need to trigger the backfill even for new events to start being collected?

**Comment by rachellerathbone** [comment]
Hey @NathanHazout. Events for any newly added repo, whether you've given permission to access all or only selected repos, you will need to trigger a backfill. Essentially, when a new repo is added in GH, our app has no idea this has happened. Even if you go into your GH settings and add the new repo to the list we have permissions to access, there is no way for our app to know of this change because, unfortunately, GH does not send any new data to us that would make us aware of this change. The only we can find new repos is when a backfill is triggered. At this point, a request is sent to GH, and our app can then discover any new repos that we have access to and make a connection.

**Comment by NathanHazout** [comment]
Understood. Thanks

**Comment by abernix** [comment]
@rachellerathbone 👋 Are you sure the [`installation_repositories `](https://docs.github.com/en/webhooks/webhook-events-and-payloads#installation_repositories) GitHub webhook wouldn't be emitted to the GitHub Application when this repo-added event occurs to an existing application (with either an `added` or `removed` event)?

I'm almost certain this webhook is specifically intended for the use case of eliminating the problem of when a repo is added to an existing application.
