### ISSUE TITLE
Cannot connect App to My Organization

### ISSUE THREAD

**Issue by mattlavinder** [atlassian/github-for-jira#1082]
I have tried 5 times to connect this app to our organization and I get no where.  It never connects.  I believe I have to use the Github process, because, if I install Github in Jira, I press the button to connect the applications and I only see an option to connect it to my personal Github repository.  

When I follow the process through Github, Github seems to have setup the connection to Jira, but the Jira apps seems to have know knowledge of it.  I uninstalled the app in both places and redid the whole thing from start to finish and it still didn't work.

**Comment by mboudreau** [comment]
Do you have IP allowlisting enabled on your organization?  If you do, you also need to check the box `Enable IP allow list configuration for installed GitHub Apps` so that our app can actually communicate with your organization.

Please let us know if this has solved your issue. We are currently working on making this much more visible in the UI when it happens.  Thanks.

**Comment by n3wt0n** [comment]
@mboudreau I have the exact same problem, tried to install the integration between Jira and our Org in GHEC, the app installs in Jira and in GitHub, but at the end of the process Jira keeps saying "No GitHub organizations with Jira installed."

Tried like 20 times, and no luck.

And we don't have IP allowlist enabled.

This is pretty urgent for us

**Comment by rachellerathbone** [comment]
Hey @mattlavinder. 

Jira install flow: This might be a dumb question but want to rule out the smallest possibilities so we can help unblock you. Have you tried signing out of your personal GH account and seeing what happens? If I want to connect the app to diff GH accounts I have, I need make sure I'm not signed into the account I don't want to connect to, otherwise, that is where I will be redirected. 

Installation flow from GH: An update to the app got merged a couple of weeks ago that should resolve the issue you're facing with this installation flow. Once you enter your domain in the input field seen in the screenshot and click continue 

<img width="607" alt="Screen Shot 2022-03-14 at 4 57 02 pm" src="https://user-images.githubusercontent.com/37155488/158113558-2f2b19d4-9c57-48a8-ae17-819ac00940b2.png">

you should land on the GitHub configuration page.

Please let me know if you are still having issues.

**Comment by nicholasgibson2** [comment]
I'm experiencing the same (or similar) issue. I installed the app in Jira, installed the app in GitHub, but I'm stuck on "Connect a GitHub organization to your Jira site". When I click the connect button nothing happens in the UI, dev console shows status code 500 Internal Server Error.

**Comment by rikur** [comment]
@rachellerathbone I've never seen that UI while connecting GH to Jira. I get 500 Internal Server Error as well.

**Comment by decador** [comment]
As I connected with one account now I am uninstalling and reinstalling but it somehow can only connect to that one account otherwise on installation page where we connect the jira site name to github .. it get stuck and in console give 401

**Comment by rachellerathbone** [comment]
Hey @nicholasgibson2. Is this still an issue for you? If @nicholasgibson2 @rikur and @decador could try and go through the flow again and send me the name of your jira hosts e.g. https://**.atlassian.net, I could take a look in our logs to see if I can figure out what is going on.

**Comment by rachellerathbone** [comment]
Hey all. As we haven’t heard from you in almost 2 months, I’m going to go ahead and close this issue. Please feel free to reopen if you still need assistance.
