### ISSUE TITLE
Other random ideas

### ISSUE THREAD

**Issue by andymckay** [atlassian/github-for-jira#11]
A list of other ideas, none of which are required for V1.

- [ ] Creates a branch in GitHub from a JIRA ticket
- [ ] Displays Pull Request 'state' in JIRA - [open, closed], is mergeable, are all CI passing, state of reviews
- [ ] Modifies a Pull Request in GitHub from a JIRA ticket - Merge, Close
- [ ] Orchestrates branches or releases from JIRA
- [ ] Replaces GitHub issues with JIRA Issues
- [ ] Replaces GitHub Projects with Atlassian Project Boards
- [ ] Displays JIRA content in GitHub

**Comment by Shukuyen** [comment]
> Creating a branch from a Jira ticket is possible if we add an issue content module to Jira. That would allow us to one-click create a branch from an issue.

Hey there, are there plans to implement this? We are thinking about switching from Bitbucket to Github and this is one pain point. Thanks!

**Comment by rachellerathbone** [comment]
Hi @andymckay. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by rachellerathbone** [comment]
Hi @andymckay. We've looked through your list. It looks like some of these things have been implemented/in progress since you opened this issue. A few of the others some possible and some we need more context from you. Creates a branch in GitHub from a 

- [ ] Creates a branch in GitHub from aJIRA ticket - this is something that is currently in the works so stay tuned for this one.
- [ ] Displays Pull Request 'state' in JIRA - [open, closed], is mergeable, are all CI passing, state of reviews - already implemented
- [ ] Modifies a Pull Request in GitHub from a JIRA ticket - Merge, Close - have opened a ticket for this. Stay tuned.
- [ ] Orchestrates branches or releases from JIRA - can you explain this one a little more? What do you mean by 'orchestrates'
- [ ] Replaces GitHub issues with JIRA Issues - can I get some more context around how you envision this working? Do you mean that if I created an issue in Jira and there was already a similar issue in GitHub, that it would delete the issue and open a new one?
- [ ] Replaces GitHub Projects with Atlassian Project Boards - definitely need more context around this one. Not sure if this is something we'd be able to do with the GitHub for Jira app as this sounds like something that would be on the GitHub side of things.
- [ ] Displays JIRA content in GitHub - what content? where?

**Comment by rachellerathbone** [comment]
A couple of the above items are in progress. That said, given there has been no response for a veerrrrrry long time, I'm going to go ahead and close this. Please feel free to reopen if you wish to discuss further.
