### ISSUE TITLE
Can't see the development panel on the issues new view

### ISSUE THREAD

**Issue by dosteso** [atlassian/github-for-jira#1100]
Hi from atSistemas, Atlassian Platinum Partner.

I have linked Jira issue with my GitHub repository, while in the old view I can see the branch, commit and pull request I have done, in the new view issue I don't see anything at all. I've check the issue layout and the add-on's permissions but everythings seems to be ok. Please see the attached screenshots.

Could you give me a clue?

Thanks and nice regards.

![image](https://user-images.githubusercontent.com/100126855/154983638-78ecf413-a756-4d7e-9fc4-1ce367e4fbb3.png)
![image](https://user-images.githubusercontent.com/100126855/154983696-d4c00bcf-85fd-4db0-97dc-eff046aa0355.png)
![image](https://user-images.githubusercontent.com/100126855/154983742-8f623752-3459-4024-8770-33cdcfc560ec.png)
![image](https://user-images.githubusercontent.com/100126855/154983787-83aa355d-8e16-43e7-8259-98b7927d43e2.png)

**Comment by mboudreau** [comment]
Hi @dosteso,

Since the data is getting into Jira (as per your old view), which means our integrations works, my guess is some kind of permission issues on the Jira side.  If you'd like to get help on this, I'd suggest you contact [Atlassian Support](https://support.atlassian.com/contact/) as they're better suited to help you with this issue.

Hope this helps.  I'm going to close this ticket now but feel free to reopen if there's still an issue.

Cheers.
