### ISSUE TITLE
How do I only allow certain projects to have access to GitHub integration?

### ISSUE THREAD

**Issue by lofgrenl** [atlassian/github-for-jira#1136]
Instructions online do not work as I do not have a "Git" menu item: https://bigbrassband.atlassian.net/wiki/spaces/GIJDC/pages/509444154/Setting+Project+Permissions

None of that exists - I am using JIRA cloud.

**Comment by mboudreau** [comment]
That documentation is for a completely different app.

There is no "per project" permissions in this case as Jira Apps are global per Jira cloud address.  Usually, just creating and using the correct ticket ids is more than enough to create separation between projects since this App is mostly a 'read from Github, add to ticket" type of integration and there isn't a lot of actions that are done from Jira.  As such, there's no risk involved as there's nothing a user can action with the app, they need to have enough access with jira or github to do anything.
