### ISSUE TITLE
Invalid value

### ISSUE THREAD

**Issue by poldinik** [atlassian/github-for-jira#1382]
After adding organization

I got this error:
{"errors":[{"msg":"Invalid value","param":"installation_id","location":"query"}]}

**Comment by mboudreau** [comment]
@poldinik we're still awaiting your response.  Please respond by end of the week or else we'll close this issue, thanks.

**Comment by experimatt** [comment]
I'm seeing the exact same error at this URL after trying to connect JIRA to a github organization: https://github.atlassian.com/github/setup?setup_action=request

```
{"errors":[{"msg":"Invalid value","param":"installation_id","location":"query"}]}
```

**Comment by philldorrell-ai** [comment]
Getting the same as @experimatt

**Comment by rahulpawar08** [comment]
Getting the same Error, refer below:
Url - https://github.atlassian.com/github/setup?setup_action=request

{"errors":[{"msg":"Invalid value","param":"installation_id","location":"query"}]}

Can we have an ETA for the issue, any work around will also do, this is kinda a blocker to proceed further

**Comment by bgvozdev** [comment]
Hey folks, I'm pretty sure that you are trying to install the app in an org where you don't have enough permissions. This is the screen that you should see for successful installation, with "Install" button.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/20631664/186400289-4fea649e-9ca7-4912-b35a-23a159b11441.png">

If I try to install the app in an org where I'm just a member, not an owner, I'll see a "request" button instead.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/20631664/186400581-1441eea8-534f-46bb-89a5-eaea3779be8f.png">

That's a pity that the app doesn't show a correct message for such case (we will tackle that), but nevertheless even if it had it wouldn't have helped because you need an owner of the org to act in order to install the app. 

Please let us know if it makes sense.

**Comment by philldorrell-ai** [comment]
Yes, when my boss approved the installation, everything worked and we are now integrated.
However seeing a json object with an error message in it didn't make that particularly obvious

**Comment by bgvozdev** [comment]
Yeah, agree. As being mentioned, we will be looking into fixing it.

I'm closing the issue, please feel free to reopen if you have more questions.

**Comment by jurkstas-gard** [comment]
I am still getting this same behaviour. Not fixed?

> Getting the same Error, refer below: Url - https://github.atlassian.com/github/setup?setup_action=request
> 
> {"errors":[{"msg":"Invalid value","param":"installation_id","location":"query"}]}
> 
> @mboudreau - Can we have an ETA for the issue, any work around will also do, this is kinda a blocker to proceed further
