### ISSUE TITLE
How do we check progress of the sync?

### ISSUE THREAD

**Issue by sawilde** [atlassian/github-for-jira#1448]
Over the weekend I noticed that my Jira automation that relates to when cards are Deployed stopped working.

I believe this is because the Github for Jira integration is not syncing properly and seems to be hung at 27/59 repositories.

I restarted the backfill operation and it moved steadily along and with 30 mins it was back at the same stage 27/59 and it does not move forward.

Does this mean there is a problem with one of the repositories? How do I determine which repository it is, as I see no feedback from the backfill process?

![image](https://user-images.githubusercontent.com/297165/182498301-d386c527-b41b-4ec6-801e-b5bf25cdde6a.png)

I did count down to the 27th repository in the list (assuming they are evaluated on order) but it is a small repository and so I can't see how it would be causing an issue.

I am stumped as to what to try next.

**Comment by sawilde** [comment]
Okay two days on and we are now at 55/59 - at least deployments are syncing again for the repository for which that action is recorded against

**Comment by rachellerathbone** [comment]
Hey @sawilde. Apologies for the slow response to this one. The time to complete a backfill is entirely dependent on how much historical data there is: if there's a small amount, a sync can complete within minutes. However, if there is a lot of data associated with the repos you are trying to connect to, then this can considerably increase the time.

We've recently updated and improved our syncing algorithm, so should you need to backfill data again (because you add new repos/delete repos and want the right data showing up in Jira) it will complete faster than it previously did. Additionally, you now have the option to set a backfill date so we only pull in data from that date forward, instead of pulling in every piece of data from the time the repo was created.

![Uploading Screen Shot 2022-08-25 at 3.48.53 pm.png…]()

**Comment by sawilde** [comment]
Hi, I think that would definitely help as really we only care for the past year.

Is data older than the entered date removed from Jira or is it retained? I am thinking about the details on old cards that are done but a curious mind investigating an issue may find useful.

**Comment by rachellerathbone** [comment]
If you set a date and trigger a backfill, it will overwrite the existing data in the db. So yes, we would no longer store any data prior to the selected data.

**Comment by sawilde** [comment]
@rachellerathbone thankyou

**Comment by rachellerathbone** [comment]
You're welcome at @sawilde. You have given me an interesting idea that I'm going to scope out with the team: adding the ability to handpick repos to backfill to specific dates. This would allow you to backfill most repos to one date, while providing flexibility for others where you may wish to go further back.
