### ISSUE TITLE
An old github profile picture is being used when my account is linked to a pull request

### ISSUE THREAD

**Issue by joeythomaschaske** [atlassian/github-for-jira#1780]
When I create a pull request, the associated branch shows up on the jira story which shows an outdated gravatar image that was changed years ago.

**Comment by mboudreau** [comment]
Hm, interesting, let me bring this up with the Jira team, I'm guessing there's some kind of caching going on instead of updating to your latest avatar.

**Comment by joeythomaschaske** [comment]
I also opened up a support case with github support and they said I can log into Gravatar and update the image there. 

I created this account more than 10 years ago and don't remember using Gravatar. Regardless the integration should probably show the user's current github profile picture

**Comment by mboudreau** [comment]
@joeythomaschaske I was able to get more info.  Am I correct to guess that your github account email is not the same email as your Jira account?  We've done a change recently where we don't use the Github avatar for GDPR reasons for our development detail panel, so everything is linked to the Jira profile.  If the email matches to the profile, it uses your Jira avatar, but If you don't (as in email doesn't match) then the gravatar is used a fallback.

I know that this is not exactly a great experience.  In the future, we hope to add profile linking/multiple emails to your Jira profile for easier integrations, but at the moment this is not possible, sorry.

I'm going to close this issue as this is outside the scope of this integration and since you've already created a support ticket, they'll be much better a answering and giving updates on this issue.

Cheers.

**Comment by joeythomaschaske** [comment]
Yes that is correct! Thanks for the explanation!

**Comment by JoppeDC** [comment]
Ran into the same issue. I feel that using Gravatar is not a proper solution here. The integration should check *all* email adresses related to a github account for a Jira equivalent. My secondary github email, is my Jira email, but its not linking correctly.
