### ISSUE TITLE
All users showing as "user" in Pull Requests Tab

### ISSUE THREAD

**Issue by bmacinanti** [atlassian/github-for-jira#1794]
![image](https://user-images.githubusercontent.com/16087586/207361224-8bab6c32-25df-4399-8961-6f9385d0179f.png)

**Comment by birdsarah** [comment]
I have the same problem. In my case two out of dozens of my users do show up correctly. The two that do show up correctly I believe it's because their github usernames that match their Jira username. 

It is not possible for many folks to get the github username that matches their jira username. 

It would be great if this connection could be made on, say, the commit email address matching the jira email address...or some other mechanism that's configurable.

**Comment by rachellerathbone** [comment]
Hey all. Unfortunately, this regression is the result of a upstream team changing the way they store data. A team mate of mine is working on a doc to outline what can be done to remediate this via your GH settings, until we find a longer-term strategy.

I'll send the link through once it's ready.

**Comment by rachellerathbone** [comment]
Our SUPPORT docs have been updated with more info and a temporary workaround https://github.com/atlassian/github-for-jira/blob/main/SUPPORT.md#unmapped-users Unfortunately, this is not the most ideal solution but it is the best we can do at this point in time. We're trying to coordinate with the team that made the changes to see if there is a way to return this functionality for all users.

**Comment by bgvozdev** [comment]
Duplicate https://github.com/atlassian/github-for-jira/issues/1794

**Comment by Euclidite** [comment]
@rachellerathbone Is there any update on this issue? Making our private/corporate emails public to everyone is a pretty big ask just to get PRs linked up to the right user. Even a "manual mapping" would be more preferable.

**Comment by stguitar** [comment]
@rachellerathbone heavy add to @Euclidite here... is there really no other way??

**Comment by Radek-Pysny** [comment]
@rachellerathbone, that issue is already closed. Does it mean that no future improvement is planned? I have faced the same issue and tried to change my profile settings according to the mentioned documentation, but it did not work for me. There has to be some other dependency or hidden flag or so... Perhaps someone forget to update that document.
