### ISSUE TITLE
Private Github emails

### ISSUE THREAD

**Issue by SimplesSimon** [atlassian/github-for-jira#181]
I'm trying to set up Github integration with our Jira projects. It all works fine *unless* I make my email address private on Github, where the integration fails. I initially logged this as a support issue last November but was told that it was a feature of your implementation and that I should follow this repo for updates. 

I now see the issue is still unaddressed. Are there any plans to do so? Our developers all use private emails, so this is a big problem for me.

**Comment by tcbyrd** [comment]
Hey @SimplesSimon thanks for bringing this back up. The main problem behind this is that Jira maps smart commits based on when the e-mail address of the author maps to a user in Jira. Without that we'd have to modify the app to request additional permissions to read a user's private e-mail address, or the integration would have to manually call the smart commit transitions.

One feature we did release recently that may help is to make use of an [`on-behalf-of` trailer](https://help.github.com/en/articles/creating-a-commit-on-behalf-of-an-organization). We'd have to experiment with it, but I feel like it could work since the commits could contain an Organization-specific e-mail address that maps to an admin user in Jira. Then all commits in Jira would show up as coming from that single account. Would that be an acceptable solution? It would mean all commits you want to send over to Jira would also have to use that e-mail address in the commit trailer, but it would allow users to keep their regular e-mail address private.

**Comment by SimplesSimon** [comment]
Yeah, it's a tricky challenge @tcbyrd. Thanks for getting back to me. It might be worth experimenting with the on-behalf-of trailer but for me the challenge isn't technical but behavioural. I'm trying to make the overhead of Jira as minimal as possible for devs. Adding more syntax to Smart Commits may make adoption difficult. We'll have to see.

**Comment by tcbyrd** [comment]
The other option is we make the integration manually call the smart commit/transition API. We had this feature initially, but removed it because it was causing duplicate transitions when the author matched a user in Jira. There's an option there to prevent transitions from happening automatically if we know the integration has to manually call API, but for security reasons we opted to let it only happen if the e-mail matches.

I'll run through some experiments here to see what feels "right" and get your feedback.

**Comment by bjchambers** [comment]
I'm interested in this too. I'd rather not require disabling private e-mail in order to use the Jira integration, especially since that would affect my account in all repositories, not just those that are integrated with Jira.

Any progress here?

If this is too difficult, would it be possible to allow an option like "Block command line pushes that expose my email" option but only affecting *public* repositories? That would at least allow me to continue protecting my e-mail address in public repositories, while using my e-mail address in the private repositories linked to Jira.

**Comment by EduSemensati** [comment]
+1

**Comment by rachellerathbone** [comment]
Hi @SimplesSimon. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by rachellerathbone** [comment]
Hi @SimplesSimon. Given this issue was opened over 2 years ago, before me and the team start working on a potential solution to this, we'd like to know if you were able to solve your issue by using 'on-behalf-of trailer' as recommended by @tcbyrd.

**Comment by EduSemensati** [comment]
Since @SimplesSimon did not come back to it, let me add my perspective:

We have not yet experimented with the on-behalf commit syntax. At this point, changing local git configs to use our corporate domain address is part of our instructions for how our GitHub users can enable SmartCommits in Jira.

However, this is an extra step which a lot of users are either (1) not going through or (2) having issues doing so. Both limit functionality adoption and troubleshooting time for our central team.

That being said, it would much easier if the integration app had extra permissions to check the GitHub User email address, since everyone in our company has two email address configured in their GitHub Account: personal email and corporate domain email (which is a requirement to join our GitHub organization). On top of that, plenty of our users change the configuration to keep emails privates, so the GitHub placeholder is used instead.

It would be awesome if this is all transparent for the user and the app itself cross check email addresses and do the proper mapping. Not sure if this is possible though.

**Comment by ccrolf** [comment]
Hi,

Can [Automation for Jira (A4J)](https://www.atlassian.com/software/jira/features/automation) replace your usage of smart commits? That would allow you to configure the automation once and for all in a project, removing the need to add commands in the commit message.

Cheers,
Christian

**Comment by souravjamwal77** [comment]
Hi @rachellerathbone, Is this issue resolved?

**Comment by mboudreau** [comment]
@souravjamwal77 Could you try to see if it's still an issue.  We've made some changes around this area for other reasons and I'm not sure if it's fixed the issue.

**Comment by souravjamwal77** [comment]
No, I made many commit with issue key in commit messages in both of the below formats
```
git commit -m "MYH-7 Add new config file"
git commit -m "MYH-7 #comment Add assets files to dir"
```
But It didn't work so I created a branch with the same name as Issue Key like **MYH-6**, But it also didn't work.

**Comment by rachellerathbone** [comment]
Hey @souravjamwal77. Were you able to see if A4J would work as a replacement as per the suggestion made by @ccrolf last month?

**Comment by souravjamwal77** [comment]
Hi @mboudreau @rachellerathbone, I can see my commits, branches and PRs in JIRA now. I just authenticated GitHub in JIRA again and it worked. Thank for your support.

**Comment by rachellerathbone** [comment]
Sorry I missed your response @souravjamwal77. Glad everything is working for you now. Please let us know if there is anything else we can help with.
