### ISSUE TITLE
Users unable to find repos that they have access to

### ISSUE THREAD

**Issue by cguttapalli** [atlassian/github-for-jira#1885]
We are trying to create a branch for a github repo from Jira. Some of the users are unable to browse all the repos available in Github. For some users the repo search option is not working. Even the org level admins are unable to find the repos.

**Comment by Ryan-Yuanqing-Jiang** [comment]
Hi, thanks for using the Github-for-Jira app and reaching out to us! We'd love to help resolve your issues.

Due to the limited resources we have in the team it's a bit difficult to attend to all the Github issue support requests. 

It'd be great if you could please raise a support request with some more details of your situation via our [support portal](https://support.atlassian.com/jira-software-cloud/), where our support engineers could assist you resolve the issue before escalating to our development team.

Thanks!
