### ISSUE TITLE
Smart Commits are not transitioning the state of the Jira issue

### ISSUE THREAD

**Issue by SuriDotInc** [atlassian/github-for-jira#206]
We have integrated Jira with GitHub, when committed on GitHub, the commits are showing up in Jira but the transition of the state is not working, we tried use various states that we have and finally reaching out for the help. The log activity(Time taken for the work) is also not being applied on the Jira ticket, I made sure the email address used for GitHub and Jira is the same, and still no luck. Can you please pass some ideas on how to troubleshoot.

Thanks,

**Comment by ciarancourtney** [comment]
I'm having the same issue, although I'm only testing the time feature. Is it possible tempo timesheets would interfere with native jira time logs?

**Comment by jnraine** [comment]
@SuriDotInc Could you post an example of some text that isn't behaving as you'd expect it? That should help us track down the problem. Thanks!

**Comment by Happy-Ferret** [comment]
@jnraine 

I'm having the exact same issues. The Development Panel inside Jira actually behaves properly, anything else fails.

I can't get Jira Tasks to transition, and references to Jira tickets don't resolve in GitHub either.
i e in the GitHub Commit overview, commit titles/bodies will not actually link back to Jira. They'll show up as verbatim text. References do work inside GitHub Pull Requests though. Not sure if that's a shortcoming of GitHub or of this plugin.

Here are some test commit messages:

```
Update main.c

JGT-5 #close
```

```
Update README

[JGT-7] #resolve 
```

```
[JGT-8] #resolve

JGT-8 Test
```

Neither of those does anything, at all.

**Comment by matt2000** [comment]
Smart commits aren't working for me either, e.g.,
```
$git commit -am 'DE-1 #ready'
$git commit -am 'DE-1: #comment fake progress!'
```

**Comment by kauanmocelin** [comment]
Same to me, comments work but transitions not :(

**Comment by naru1234567** [comment]
Same with me. Comments working but transition not working

**Comment by Divya-Dias** [comment]
> I'm using Scrum workflow and when commit with #done it works.

Hello @kauanmocelin  Could you please share a screenshot of your workflow? Is done a status in your workflow? 
I am having the same issue reported here and can't seem to get the transitions working. Everything else - comments, time log and commit info appear in JIRA as expected.

**Comment by kauanmocelin** [comment]
@Divya-Dias create a new project using Scrum template, my project follows this template as default. Status is: todo, in progress and done.

**Comment by Divya-Dias** [comment]
@kauanmocelin That wouldn't be possible as we have complex workflows in place. Is your org using the nextgen project or classic?

**Comment by rachellerathbone** [comment]
Hi @SuriDotInc. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Can you please let me know if you're still experiencing this issue so my team can investigate.

**Comment by Neoware-ai** [comment]
Yep it still exists

**Comment by firstdivision** [comment]
I had to make sure my github.com email address was set up correctly.  Including unchecking "Keep my email address private".

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

**Comment by sushantoghosh** [comment]
Issue exist for Jira Work management too, have used git commit messages with transition commands like

git commit -m "test message TEST-495 fixed #transition #BACKLOG first comment to check jira github integration"  

git commit -m "test message TEST-495 fixed #BACKLOG first comment to check jira github integration"  

git commit -m "test message TEST-495 fixed #transition BACKLOG first comment to check jira github integration"  

git commit -m "test message TEST-495 fixed  #'BACKLOG' first comment to check jira github integration"

**Comment by mboudreau** [comment]
Hi everyone, we're investigating this issue.  please provide me with your atlassian domain so that I can turn on the logs for smart commit to see what's going on, thanks :)

**Comment by HenryQW** [comment]
@mboudreau rss3. Unable to get it working.

**Comment by gusmanwidodo** [comment]
smart commit to link the ticket is still not working

**Comment by rachellerathbone** [comment]
Hey all. Just wanted to check in to see if everyone/anyone was still having issues with smart commits. I personally haven't used them before so just did some investigating and discovered the following:

**Your email in Jira and GitHub must match**: when I tested out smart commits with my GitHub account that points to my personal email and Jira account attached to my work email, nothing happened. This is mentioned in Jira's smart commit documentation but is weirdly placed in the table that describes how to use comments. I'm going to see if I can track down the team that owns smart commits and get them to update their docs to make this point more obvious.

<img width="779" alt="Screen Shot 2022-10-24 at 4 06 00 pm" src="https://user-images.githubusercontent.com/37155488/197452165-5199e8ee-22bc-4c75-9862-b74ef4f8ef01.png">

**You have to uncheck to uncheck 'Keep my email addresses private' in GitHub**: ran into the same issue here. Didn't matter what smart commit I tried, while this box was checked, no smart commit magic. I couldn't find a reference to this anywhere in the smart commit docs so will pester the team who owns it about adding this as well. To uncheck this box just go to your settings in GitHub > Emails > find the  'Keep my email addresses private' and uncheck the box. 

This is obviously not ideal if you want to keep your email address private but, unfortunately, when it's checked, GitHub doesn't send your email address in the payload when a webhook is fired so Jira determines that as a mismatch and fails to meet to above criteria of having the same email addresses in both accounts.

After ensuring my email addresses were the same **and** unchecking that box, transitions started working for me 🎉 

Two more things I'll call out for transitions: I was using #done to transition my issues as this is the title for completed item in my workflow. #closed/#complete did not work for me so please make sure you using the correct naming to transition your issues. Also, I'm using a very basic workflow of todo > in progress > done and noted I could move tickets from and to anywhere on my board. However, if you are using a move complex workflow where, for instance, you can't jump columns, you may need to make sure that your issue is in the correct column before trying to transition i.e. some admins may block you from dragging an issue straight from todo to done, and may require you to first move it into the in progress column.

**Time commits need to be enabled and added to the issue type for time tracking to work**: this one took me a minute to figure out. I checked the sites settings and noted 'Copying of comments to work description' is in fact enabled (this one is [referenced in the docs ](https://support.atlassian.com/jira-software-cloud/docs/log-time-on-an-issue/)😄) but still wasn't seeing anything. 

<img width="788" alt="Screen Shot 2022-10-24 at 4 11 30 pm" src="https://user-images.githubusercontent.com/37155488/197453660-d35a114c-917e-4f18-96c7-7655835d9c4d.png">

Thankfully, the smart commit docs helped me out again. Clicking on [Read more about configuring time tracking](https://confluence.atlassian.com/adminjiracloud/configuring-time-tracking-818578858.html) in the doc I just linked to led me to a page that outlined **everything** that needs to be done for time tracking to work. I needed to add time tracking to any issue type where I wanted that to be visible e.g. for issues of type story

<img width="1122" alt="Screen Shot 2022-10-24 at 3 56 16 pm" src="https://user-images.githubusercontent.com/37155488/197453747-7626d02b-1024-4e68-9b68-7f56bf69adbc.png">

After adding that, time tracking started working 😄 NOTE: in order to enable time tracking and add it to stories/issues/bugs you will need to be an admin/get an admin to do that for you.

One callout I will make here: I tested this is a couple of project types. I was able to get time tracking to work in a business project and a software project that was of type 'scrum'. However when I tested a software project that was of type kanban, time tracking did not work despite having all my settings (according to the docs) correctly configured. I'm not sure if there is another setting or if time tracking simply isn't supported for this board type. Will ask the team that owns smart commits when I track them down.

@Happy-Ferret You are correct, the issue keys do not link back to the issue in Jira but this is because we currently do not support that. We would need to look into unfurling commits, like we do for PRs and issues. I can chat with my team about this.

Hope this helps everyone.

**Comment by mboudreau** [comment]
Hey everyone, I'm going to close this ticket as it appear that most of the issues is based on what @rachellerathbone just mentioned above.  If people are still having issues after trying the above, please let us know here and I'll open it back up.

Cheers.

**Comment by antonsalim91** [comment]
> Hey all. Just wanted to check in to see if everyone/anyone was still having issues with smart commits. I personally haven't used them before so just did some investigating and discovered the following:
> 
> **Your email in Jira and GitHub must match**: when I tested out smart commits with my GitHub account that points to my personal email and Jira account attached to my work email, nothing happened. This is mentioned in Jira's smart commit documentation but is weirdly placed in the table that describes how to use comments. I'm going to see if I can track down the team that owns smart commits and get them to update their docs to make this point more obvious.
> 
> <img alt="Screen Shot 2022-10-24 at 4 06 00 pm" width="779" src="https://user-images.githubusercontent.com/37155488/197452165-5199e8ee-22bc-4c75-9862-b74ef4f8ef01.png">
> 
> **You have to uncheck 'Keep my email addresses private' in GitHub**: ran into the same issue here. Didn't matter what smart commit I tried, while this box was checked, no smart commit magic. I couldn't find a reference to this anywhere in the smart commit docs so will pester the team who owns it about adding this as well. To uncheck this box just go to your settings in GitHub > Emails > find the 'Keep my email addresses private' and uncheck the box.
> 
> This is obviously not ideal if you want to keep your email address private but, unfortunately, when it's checked, GitHub doesn't send your email address in the payload when a webhook is fired so Jira determines that as a mismatch and fails to meet to above criteria of having the same email addresses in both accounts.
> 
> After ensuring my email addresses were the same **and** unchecking that box, transitions started working for me 🎉
> 
> Two more things I'll call out for transitions: I was using #done to transition my issues as this is the title for completed item in my workflow. #closed/#complete did not work for me so please make sure you using the correct naming to transition your issues. Also, I'm using a very basic workflow of todo > in progress > done and noted I could move tickets from and to anywhere on my board. However, if you are using a move complex workflow where, for instance, you can't jump columns, you may need to make sure that your issue is in the correct column before trying to transition i.e. some admins may block you from dragging an issue straight from todo to done, and may require you to first move it into the in progress column.
> 
> **Time commits need to be enabled and added to the issue type for time tracking to work**: this one took me a minute to figure out. I checked the sites settings and noted 'Copying of comments to work description' is in fact enabled (this one is [referenced in the docs ](https://support.atlassian.com/jira-software-cloud/docs/log-time-on-an-issue/)😄) but still wasn't seeing anything.
> 
> <img alt="Screen Shot 2022-10-24 at 4 11 30 pm" width="788" src="https://user-images.githubusercontent.com/37155488/197453660-d35a114c-917e-4f18-96c7-7655835d9c4d.png">
> 
> Thankfully, the smart commit docs helped me out again. Clicking on [Read more about configuring time tracking](https://confluence.atlassian.com/adminjiracloud/configuring-time-tracking-818578858.html) in the doc I just linked to led me to a page that outlined **everything** that needs to be done for time tracking to work. I needed to add time tracking to any issue type where I wanted that to be visible e.g. for issues of type story
> 
> <img alt="Screen Shot 2022-10-24 at 3 56 16 pm" width="1122" src="https://user-images.githubusercontent.com/37155488/197453747-7626d02b-1024-4e68-9b68-7f56bf69adbc.png">
> 
> After adding that, time tracking started working 😄 NOTE: in order to enable time tracking and add it to stories/issues/bugs you will need to be an admin/get an admin to do that for you.
> 
> @Happy-Ferret You are correct, the issue keys do not link back to the issue in Jira but this is because we currently do not support that. We would need to look into unfurling commits, like we do for PRs and issues. I can chat with my team about this.
> 
> Hope this helps everyone.

Hi, what if my primary email is not the same as the one used in Jira, but one of my secondary/backup emails is the same one used in Jira, will it still work?

**Comment by SpoonOfDoom** [comment]
I would vote to reopen this, because it cannot seriously be the solution that
a) I have to make my GH email address public
and
b) the email addresses in both systems must match?

I have little interest in making a new github account with a matching email just to get smart commits to work. Surely we can find a better solution?

**Comment by khanmannan** [comment]
> I would vote to reopen this, because it cannot seriously be the solution that a) I have to make my GH email address public and b) the email addresses in both systems must match?
> 
> I have little interest in making a new github account with a matching email just to get smart commits to work. Surely we can find a better solution?

I agree to that. We definitely need a much better solution.

**Comment by catosh** [comment]
I am still not able to update the time spent. I wonder if this is related to the Premium plan instead of Ultimate in gitlab, or the usage of standard plan instead of premium in Jira. Also, what if I have a team managed project instead of a company managed project? I am relly interested in the time tracking for smart commits but it seems that I not blessed by it working correctly.

**Comment by strakers** [comment]
> I would vote to reopen this, because it cannot seriously be the solution that a) I have to make my GH email address public and b) the email addresses in both systems must match?
> 
> I have little interest in making a new github account with a matching email just to get smart commits to work. Surely we can find a better solution?

@SpoonOfDoom  This is a little late, but you can add a secondary email to your github (the one you use for JIRA) and make that public. I use this for both my work and freelance email addresses on the same account.

**Comment by SpoonOfDoom** [comment]
@strakers thanks for the heads up. However I found another workaround: It was enough for me to create a local git profile that uses the same email as the one in Jira, this way I didn't have to make anything public in Github.
