### ISSUE TITLE
Issue showing build failed even when latest passed

### ISSUE THREAD

**Issue by M-Whitaker** [atlassian/github-for-jira#545]
Hi,

I have a CI setup with GitHub actions and it works well. One thing I am slightly confused about is why on the main issue screen it shows failing when I have run later builds which have passed so I would not expect this behavior.

Thanks for the new features 😄

**Comment by atrigueiro** [comment]
Hi @M-Whitaker,

Thanks for raising that. This is actually the intended behaviour.
Right now, the order of what is shown in the summary is:
1. Failed builds
2. Successful builds
3. Any other build state

So since you have a failed build, point 1 is shown as it has a higher priority.

We do agree that is slightly confusing, and we have raised an issue in our backlog to go through that with our PM. We'll keep you posted when we come up with a decision. Thanks!

**Comment by atrigueiro** [comment]
Hi @M-Whitaker 
The bug has been fixed. You shouldn’t see it happening again from now on, but please let us know if you do.

Thanks,

Amanda.
