### ISSUE TITLE
Is there a way to enforce Jira IDs in commit messages? (pre commit hooks)

### ISSUE THREAD

**Issue by Spenhouet** [atlassian/github-for-jira#664]
I'm not asking if this plugin specifically can do this but in general if it is possible to enforce Jira IDs in GitHub commit messages?

**Comment by rehangit** [comment]
The example in this tutorial is very close to what you are asking.
https://www.atlassian.com/git/tutorials/git-hooks

**Comment by mboudreau** [comment]
@Spenhouet Not with our Github app, no.  Personally, I wouldn't recommend you enforce commit messages to include a jira issue id as it would slow down the development flow with very little benefit.  If you're doing a merge commit on your PRs instead of a squash, you're adding every commit to the main branch which becomes kinda noisy.  If you really want to do that, you'll have to add a git-hook (like @rehangit mentioned) to each repository that would check if a ticket id is available.  If you're using node, then I'd recommend you [Husky](https://www.npmjs.com/package/husky) a look.

What would be better, in my opinion, is to enforce issue ids on PRs instead since one PR could comprise of many different commits, then do a squash merge so that each individual commit is not included in the branch, only the one commit that has the PR message for the specific bug fix or feature was added.  If you still want the history of that PR, it's still available as well as the original branch since it's been archived.  We currently don't have a way to enforce PR jira ids yet other than reviewers looking for it.  We have brought up this feature to have an automatic check on every PR, however there is a problem since when the merge happens, the user can still change the name or sometimes Github will not use the PR title as the commit message but instead of the first commit message of the PR - Github has some really weird logic in some places.

It's not a priority at this moment as we've just taking ownership of the app and working towards better stability and resiliency first before tackling new features. Hope you understand.

**Comment by rachellerathbone** [comment]
Hey @Spenhouet. Would [commit message hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) help with what you're trying to achieve?

**Comment by rachellerathbone** [comment]
Hey @Spenhouet. As it has been several months since we've heard from you, I'm going to go ahead and close this issue. Please feel free to reopen if you still need help with this one.

**Comment by johnmoralestrinet** [comment]
interested in this feature as we use Jira Data Center and GitHub Enterprise Cloud

**Comment by stillwaiting** [comment]
Hey @johnmoralestrinet  , the app doesn't work with Jira Data Server, it is for Jira cloud only. However, the suggestions above (using github hooks) should work for all case, as this solution is github-specific, not integration-specific.

**Comment by johnmoralestrinet** [comment]
@stillwaiting Hi Boris, is the code open source if yes then maybe we can retrofit the code to support Jira Data Center....
