### ISSUE TITLE
Missing reviewer in JIRA fir GIT Plugin

### ISSUE THREAD

**Issue by sramanadas** [atlassian/github-for-jira#671]
we need an urgent fix for JIRA Cloud on the Reviewer field.
If this cant be see, we have to do manually work each time we a do release.
 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/89778754/131326947-0ae7a7b0-8e30-4aec-8277-ff9da5733126.png)

**Comment by mboudreau** [comment]
@sramanadas I've just tried it on our Jira instance and it seems to be working correctly.

The only way I can think why this is causing this issue is because it's missing a permission in your Github App.  Please let your Github Org admin to go into the app by going to Settings => Installed Github Apps => Click edit on "Jira" app.  Under permissions, if there's an "Update Permissions" showing there, please click it to make sure the app has the sufficient permissions needed to get the Pull Request Reviewer data.

Once that's done, you can then do a Full Sync from the "Manage Apps" section in Jira (again, done by your admin) to restore any historical data that's been missing.

Please let us know how you go.

**Comment by sramanadas** [comment]
Hello Team,

We dont see any tab known as update permission. PFA the image. Syncing of JIRA and Git was already completed
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/89778754/131341199-0f285860-d05a-4ff8-9475-017c8ee4f184.png)

**Comment by mboudreau** [comment]
Hm, interesting. Your permissions look good. Can you retry the sync please?

**Comment by sramanadas** [comment]
Hello Team 

Any update

**Comment by mboudreau** [comment]
Have you retried the sync?

**Comment by sramanadas** [comment]
No Not yet, Should I resync It?

Thanks
Sramana Das

**Comment by sramanadas** [comment]
Hi Team,

I resynced it, but it doesnot work. Please help

**Comment by mboudreau** [comment]
Yes please.

**Comment by sramanadas** [comment]
Hi,

I didnot understand the previous the comment. Can you please elaborate what i have to do

Thanks 
Sramana Das

**Comment by sramanadas** [comment]
Hello Team,

Resyncing doesnot work. Can you please again look in to it.

Thanks
Sramana Das

**Comment by mboudreau** [comment]
@sramanadas yes, it's affecting a few people and we're actively looking into the solution now.  Please be patient.

**Comment by sramanadas** [comment]
Hello Team,

Any update on the issue

**Comment by rachellerathbone** [comment]
Hey @sramanadas. I've just picked up a ticket to look into this issue for you. So far, I've been unable to reproduce it myself. Could you please send me the name of your Jira site so I can take a look at our logs and see if I can find anything that indicates what the issue might be?

**Comment by ccrolf** [comment]
Hi @sramanadas please re-raise this issue if it still persists. It should be resolved and resyncing should fix old gaps in the data
