### ISSUE TITLE
Removing Deployments from Issues?

### ISSUE THREAD

**Issue by Bolensds** [atlassian/github-for-jira#675]
Kind of an odd issue we're having right now.  Now, I understand the sync is working as intended; however, I'm looking for a way to fix the issue I'm seeing.

We currently have two Atlassian Orgs with two separate Jira instances (due to a recent merger).  We have a single Github hooked up to both instances.  We also have a project titled "INFO" in each Org.  What we've discovered now is that anything tagged with "INFO-X" is syncing to both issues with that Key in both Orgs (which we don't want).  Here's what I've tried so far:

1. Re-keying the Project, then re-syncing the Github Org (Deployments stayed)
2. Moving issues to another project, then re-syning the Github Org (Deployments stayed)

What I haven't tried yet is fully _disconnecting_ the Github Org, Re-keying, then re-adding.  I know Jira Cloud "saves" an old Project Key as a "reference object" after re-keying, but has anyone tried this and had it work before?  Just curious on how I can get the current deployments removed from one INFO project, then rekey it to make sure those Deployments don't sync to it again.

Thanks!

**Comment by mboudreau** [comment]
When you resync, it doesn't remove the old "links" done to the jira tickets.   Sadly, the only way to do this is to completely uninstall the Github app in Jira, reinstall, then connect your organizations again so that it syncs up.  This is because the data is tied to the app's ID directly.

It's annoying, I know, but it's also a bit of an edge case.  The current 'resync' mechanism doesn't delete all the old data at the moment, which we should look into.  I'm very sorry for the inconvenience, but this should fix your problem.  Let me know if you have any other questions.  Thanks!

**Comment by rachellerathbone** [comment]
Hey @Bolensds. I'm going to go ahead and close this issue due to inactivity. Please feel free to reopen and reach out if you need more assistance.
