### ISSUE TITLE
How to comment an Jira issue from github action with download link of output

### ISSUE THREAD

**Issue by diptilenka** [atlassian/github-for-jira#684]
How to comment an Jira issue from github action with download link of output

like  
 - name: Comment on issue
       uses: atlassian/gajira-comment@v2.0.2
       with:
         issue: DZT-5
         comment: Test comment ${{ github.event.compare }}

**Comment by mboudreau** [comment]
Instead of asking for the solution, could you explain what you're trying to accomplish on the Jira side?  This will help us greatly to give the best advice.

Thanks.

**Comment by diptilenka** [comment]
While build the project in github , after successful build, i want to add the download link into that jira card comment to that particular card, which should be automatic after each successful build output.

**Comment by rachellerathbone** [comment]
Hey @diptilenka. Just updating you to let you know we have created an issue in our backlog to address this for you.

**Comment by rachellerathbone** [comment]
Hey @diptilenka. I chatted with the team and we believe your issue is accounted for by some work we did late last year to add support for builds and deployments. You just need to make sure your permissions are up-to-date. 

I'm going to go ahead and close this issue. If you do need further assistance and are after something slightly different, please feel free to reopen and provide some more details.
