### ISSUE TITLE
Cannot connect Github For Jira plugin to our Github organization

### ISSUE THREAD

**Issue by adamhowardprice** [atlassian/github-for-jira#719]
When I go to `https://<my-site>.atlassian.net/plugins/servlet/ac/com.github.integration.production/github-post-install-page`, and click "Connect Github Organization", the browser opens a new tab and then quickly changes the url to `about:blank`.

If I retry multiple times, eventually I will get to this page: https://github.atlassian.com/github/callback?code=60cdd516c0efa27b0a0f&state=d642e267f1d2c73f

and see an error that looks like this:

![Screen Shot 2021-09-13 at 2 54 45 PM](https://user-images.githubusercontent.com/602596/133140695-c17c7944-f831-4101-85dc-b0cef90445e8.png)

Here is a video of what happens:

https://user-images.githubusercontent.com/602596/133140768-7c61c967-e8c9-4dee-998d-a52b88659517.mp4

None of my Github automation rules are working in Jira currently, and have been broken since 7/24/21.

**Comment by rachellerathbone** [comment]
Hi @adamhowardprice. What I see in the video you provided definitely looks like our app but the path doesn't look correct. 😕 My path ends in `com.github.integration.production/github-post-install-page` but I can see yours is `com.github.integration.production/gh-a...`. Can't see all of it because it gets cut off but I definitely don't see the start of `github-post-install-page`. Could you please try uninstalling and reinstalling the app and lmk if you continue to run into the same issues.

Regarding the Github automation rules - could you provide some examples of the issues you are running into and steps to reproduce?

**Comment by rachellerathbone** [comment]
Hi @adamhowardprice. Are you still experiencing this issue?

**Comment by adamhowardprice** [comment]
@rachellerathbone Nope, resolved!
