### ISSUE TITLE
Commits to monitored repo do not show

### ISSUE THREAD

**Issue by celinakRS** [atlassian/github-for-jira#764]
We are doing an audit and noticed that one repo is missing all commits in Jira.   This repo is configured to be monitored.   I did a full sync yesterday (successfully) and still nothing.

A few examples of what is not showing on the associated linked JIRA ticket.

https://github.com/Retail-Success/Luci.Android/pull/191
https://github.com/Retail-Success/Luci.Android/pull/243
https://github.com/Retail-Success/Luci.Android/pull/295
https://github.com/Retail-Success/Luci.Android/pull/406
https://github.com/Retail-Success/Luci.Android/pull/405

We're wondering if it's due to rebasing and if this issue can be fixed?

Thank you

**Comment by rachellerathbone** [comment]
Hey @celinakRS. I'm definitely seeing logs coming through for the Luci.Android repo which confirms that it is configured correctly to trigger webhook events. However, for push events I'm seeing the message `Halting further execution for push since no commits were found for the payload` which is logged when no issue keys are found in a commit. Can you confirm that you're adding issues keys to your commits (for example a jira issue with key TEST-80 your commit message would need need to have TEST-80 somewhere in the commit message e.g. 'made a change for TEST-80 to fix bug') and provide an example?

**Comment by celinakRS** [comment]
Duh, you can close this.  Developer confirmed they were in the PR comment and not in the commit message.
