### ISSUE TITLE
Github for Jira site down

### ISSUE THREAD

**Issue by avigil** [atlassian/github-for-jira#774]
I need to change the Jira instance that we connected our github repo to. It looks like the github for jira site listed below is down currently. Is this a known issue?
https://jira.github.com/github/setup

**Comment by rachellerathbone** [comment]
Hey @avigil. This page definitely shouldn't be under maintenance so the team will need to look into what is going on here. As an alternative in the meantime, please try installing the app from Jira instead of trying to connect from GitHub. From your Jira site go to Apps in the navbar > Find new apps > search for GitHub for Jira and click on the first result, then follow the prompts to install. Please let me know if you run into any issues with that flow. 

I've created a ticket in my team's backlog for us to investigate what is going on with the `github/setup` page.

**Comment by avigil** [comment]
@rachellerathbone So, here is what I need to do. I had set up a jira cloud instance and had integrated it with github. And everything worked fine. 

But I ended up having to use another jira cloud instance. And recreated everything over there. This is because someone at our company had set up an Atlassian product with our company name. So, to use that for jira, I needed to basically take over the one he created. 

So, now I need to make sure that our organization in github is going to sync with the new jira cloud instance. I am an admin for both of those jira cloud instances.

**Comment by rachellerathbone** [comment]
@avigil. This is achievable when installing the app from Jira. After you install the app you will be prompted to 'Connect GitHub organization'. From there, you will be able to connect to any GitHub org, providing you have permissions in GH (which you would need whether you tried to install the app from Jira/GitHub).

**Comment by rachellerathbone** [comment]
Quick question: how are you navigating to `github/setup`? Are you being redirected to that page or going straight to that url?

**Comment by rachellerathbone** [comment]
Hey @avigil. We fixed the issue that was causing problems with this flow so I'm going to close this issue. Please feel free to reopen and reach out if you continue to experience problems.
