### ISSUE TITLE
How to update api token (cleaning up old DVCS connections)

### ISSUE THREAD

**Issue by kourosh-eminence** [atlassian/github-for-jira#835]
We have Github integrated with Jira. I'm getting emails warning that it is using old style tokens which are insecure.
What is the procedure for updating the tokens for the plusin?

thanks

**Comment by jgtr-coats** [comment]
We have the same issue, unfortunately I didn't configure the integration in the first place and the person who did is no longer around so it's not clear whether we migrated from DVCS to the app. All I can see is that our Jira Cloud instance is showing DVCS as not configured at the organisation level and the "GitHub for Jira" app is installed/configured. From the GitHub side the Jira Github App is installed/configured, plus I can see that there is an OAuth app called "JIRA", which I've rotated the secret for to try to flush out what is using it (I'm assuming it's not the Jira/Github app integration as that still seems to work fine since).

The email certainly seems to suggest that it's a Jira DVCS connector that is causing the issue I just can't work out where from:
> We noticed that an application, JIRA, owned by an organization you are an admin of, [SNIP], used a token with an outdated format to access the GitHub API on October 19th, 2021 at 18:07 (UTC), with a user-agent header of JIRA DVCS Connector Vertigo/1001.0.0-SNAPSHOT.

**Comment by bgvozdev** [comment]
@kourosh-eminence @jgtr-coats thank you for the response. This is a known issue. Even though DVCS integration was deprecated and replaced by the GitHub App, the tokens that had been used by DVCS still live Jira's database. We are now actively working on cleaning up the database and removing them altogether.

> I don't quite understand whether they are the same thing or different integration methods.

They are completely different. The old (DVCS) tokens are not used anymore for syncing GitHub data and can be safely revoked on GitHub side because the new integration (this app) is a GitHub App, while the old integration (DVCS) was an OAuth app.

To remove the old OAuth application (that was used for DVCS) from GitHub, you could go navigate to GitHub.com -> [You Org] -> Settings -> Developer Settings -> OAuth apps -> [App name] - > Advanced -> Delete the application

Could you please let me know if it makes sense? I'll update this issue once we finish the cleanup on our end, although even after that you might still would like to revoke the tokens on GitHub side because Jira doesn't have control over it.

**Comment by aingham** [comment]
Hi - I can understand the old DVCS token sitting around in the Jira database, but the warning email makes it sounds as though Jira has actually used it for an API call. I'd be interested to know why that is?

**Comment by rachellerathbone** [comment]
Hey @aingham. Given that it has been over a month since we last heard from you, I'm going to go ahead and close this issue. Please feel free to reopen/reach out again if you need help with anything.
