### ISSUE TITLE
Feature Request: Configurable Mapping in .github folder

### ISSUE THREAD

**Issue by joegaudet** [atlassian/github-for-jira#895]
Our production environment does not have the word production in it, which makes this integration not work correctly.

Given that you're already doing the the work to map environments based on this:

https://github.com/atlassian/github-for-jira/blob/main/src/transforms/deployment.ts#L34

It should be possible to add an environments.yml file in .github directory that would let me declare the environments.

Thoughts?

**Comment by mboudreau** [comment]
Hi Joe,

It wouldn't really work that way since we don't deploy an individual instance of the github integration for each customer.  Instead we share the resources across customers.

However, you do bring up a valid point and we do have something in our backlogs to address this issue.  We were thinking of maybe having a setting that you can specify environment names (regex?) in Jira where you configure the integration so that each individual customer can create their own environment mapping.  How does that sound?

**Comment by joegaudet** [comment]
@mboudreau just browsing the code it looks like you have access to the target repo, can you not pull data using Octokit?

Ultimately putting it on the Jira side makes more sense though, rather than crossing concerns. 

Thanks for your great work on this, anything I can do to help out?

**Comment by mboudreau** [comment]
I'm sorry, I completely misunderstood your original question.  I thought you meant the .github folder for _this_ repository, not for the ones you're trying to sync, which makes a lot more sense.  It is possible to do that, but becomes a chore for us to call the github API to get a specific file and would be prone to error. I think the Jira side solution is cleaner as that is the target we're trying to map to.

Thanks for the commendation, we're trying to continually improve the app.  To help, we always welcome PRs but it might be hard as our roadmap is on our internal jira.  Getting your feedback on things and ideas on how to improve is always helpful :)

**Comment by joegaudet** [comment]
Sounds good, do you have any indication of when we can expect this to land.

Not to rush at all, we have a cycle time + deployment frequency reporting
on a home spun thing, but would like to move to pure JIRA for reporting :)

**Comment by mboudreau** [comment]
I totally understand as it would make your life a lot simpler :)

We currently don't have a timeframe for it as we're doing some fairly low level infrastructure changes for better stability at the moment which is vehemently needed.  I'll bring it up with the team though as we've been talking about this since we released the deployments feature.  Hopefully we can get to it soon once we are done with architecture.

**Comment by joegaudet** [comment]
Awesome!

Thanks again for the great work.

**Comment by joegaudet** [comment]
Hey @mboudreau just curious if there's been any movement on this feature?

**Comment by mboudreau** [comment]
@joegaudet Not at the moment.  Right now, we're concentrating on scale, consistency and stability of the app as it's been a problem since the ownership transfer.   We're probably not going to look at this until Q2 2022.  Sorry mate.

**Comment by rachellerathbone** [comment]
Hey @joegaudet. Please see the reply to one of our other issues. I believe this is what you are after https://github.com/atlassian/github-for-jira/issues/1303#issuecomment-1226715001

**Comment by joegaudet** [comment]
@rachellerathbone sure am! thanks so much!

**Comment by rachellerathbone** [comment]
Absolutely welcome! I'm going to go ahead and close this issue. Please feel free to reopen/create a new issue if there is anything else you need help with.
