### ISSUE TITLE
Migration of instance

### ISSUE THREAD

**Issue by NenadMicic** [atlassian/github-for-jira#982]
Hi all, 

We are trying to migrate Jira Could Instance that have and use your addon "GitHub For Jira". It is important that all data related to github about development is migrated with the tickets.

Since we can’t find any documentation on this matter online, can we kindly ask you this way for help or guidance on how we can do mentioned.

Please let me know in case of any question.

Best Regards,
Nenad

**Comment by mboudreau** [comment]
Yeah, no problem.  We probably should add something to our readme about this.

When you migrate instances, you tend to lose App data because the data from integration 1 is the same, but the link to Jira is different as the ID of the instance changes when you do the migration.

But no worry though as we don't actually "store" information about your Github org on our end.  All you have to do is re-app the app to your new jira instance and connect the Github org back again.  It will then do a backfill of all historical data (this may take a little while - but it starts with the most recently updated repos) which will then show up in your jira momentarily :)

I'm going to close this ticket as I think I've answered your question, if not please let me know and I'll open it again.  Thanks.
