### ISSUE TITLE
Jira for GitHub's IP whitelisting broken?

### ISSUE THREAD

**Issue by altjx** [atlassian/github-for-jira#988]
After a few hours of troubleshooting, I realized that the "Connect" button from Jira to connect to my GitHub repository becomes enabled/disabled depending on whether or not I have IP whitelisting enabled/disabled. It works if IP whitelisting is disabled, and doesn't work if it's enabled.

According to https://github.com/atlassian/github-for-jira/issues/411, this should be fixed, but apparently the app must not have the updated IPs built in or something?

**Comment by thombergs** [comment]
Hi @altjx,

some users have reported the same issue. 

The reason for the error is that the call that checks if you're an admin in your GitHub org is blocked by the IP allowlist (which we interpret as "you're not an admin"), even though the IP addresses of our servers are listed in the allowlist. 

We just opened a support case with GitHub about this last week. I'll update this ticket here with any progress.

**Comment by thombergs** [comment]
Hi @altjx 

I followed a hunch and played around with our IP-allowlisted test org a bit more.

When I manually added the IP addresses `13.52.5.96` through `13.52.5.111` to my org's allowlist, it works!

This means there must be some issue on GitHub's side with evaluating an IP allowlist, because if I add the CIDR `13.52.5.96/28` (which contains all of the above IP addresses), it doesn't work. Also, it doesn't work if I add the CIDR or the single IP addresses to the app's managed allowlist, which an org can inherit by checking "Enable IP allow list configuration for installed GitHub Apps".

Can you please try adding the IP addresses `13.52.5.96` through `13.52.5.111` to your org's allowlist? Sorry, it's a chore with GitHub's allowlist UI :(. 

Please let me know if that works for you. I will then update my GitHub support case with the new information.

Note that the above IP range is just the "usual" range of IP addresses our servers operate from. There's no guarantee that it stays that way in the future, because Atlassian's IP range is much bigger than that (see "Outgoing connections" on [this page](https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/)). So, this can't be the end solution to the problem.

**Comment by altjx** [comment]
Nice!! Thanks for the quick reply! Will try this in just a bit and keep you posted! 🙌🏽

**Comment by thombergs** [comment]
I got a report from another user in an Atlassian support case for whom the workaround worked. So, if you are having the same issue, please add the IP addresses 13.52.5.96 through 13.52.5.111 to your org's IP allowlist (each IP address individually, not as a CIDR range) and it should work (at least as long as our servers stay in this IP range).

**Comment by altjx** [comment]
Hi @thombergs sorry for the delay. We ended up discontinuing our Jira subscription in favor of something else. Really appreciate your help!

**Comment by thombergs** [comment]
Sorry to hear that, but good luck!
